### ISSUE TITLE
setting crc in ZKCDHeader only leads to failure

### ISSUE THREAD

**Issue by cool-l** [kolpanic/ZipKit#25]
I set bit3 of ZKLFHeader.generalPurposeBitFlag (generalPurposeBitFlag == 1<<3) to delay setting crc until appending ZKCDHeader. Now the program extracts a file "file.zip", and it can be unzipped using WinRAR on Windows successfully, but fail on Mac OS.

**Comment by kolpanic** [comment]
ZipKit wasn't designed to support streaming zip archives. Merely setting generalPurposeBitFlag won't change anything. You'd also have to change it so the other fields are zeroed out, and instead appended to the data descriptor following the compressed data. If you wan't this feature, fork ZipKit and add it yourself. Sorry.
