### ISSUE TITLE
Can't decompress with original name even previously deleting destination filename

### ISSUE THREAD

**Issue by H725-79** [kolpanic/ZipKit#28]
Hi and congratulations for the work done, but I have a little problem.
I want to replace an exixting file so  I try to remove the existing file (eg cat.pdf):

+ (BOOL)unZipFileAtPath:(NSString *)source
            toDirectory:(NSString *)dir createIntermediateDirectory:(BOOL)createIntermediateDirectory
{
    BOOL isDir = NO;
    NSString *fileName; NSInteger result;
    if (createIntermediateDirectory)
        [fm createDirectoryAtPath:dir withIntermediateDirectories:YES attributes:nil error:nil];
    
    // check if "dir" exist
    if (![fm fileExistsAtPath:dir]) {
        return NO;
    }
    // check if "dir" is really a directory, otherwise fail
    [fm fileExistsAtPath:dir isDirectory:&isDir];
    if (!isDir) return NO;

    // the name of the resulting file is the last path component removing ".zip",
    // otherwise is the last path component.
    if ([source.pathExtension isEqualToString:@"zip"]) {
        fileName = [[source stringByDeletingPathExtension] lastPathComponent];
    }
    else
    {
        fileName = source.lastPathComponent;
    }
    
    // is file already existing?? if yes delete it
    if ([fm fileExistsAtPath:[dir stringByAppendingPathComponent:fileName]])
    {
        [fm removeItemAtPath:[dir stringByAppendingPathComponent:fileName] error:nil];
    }
    
    @try
    {
        ZKFileArchive *archive = [ZKFileArchive archiveWithArchivePath:source];
        result = [archive inflateToDirectory:[dir stringByAppendingPathComponent:fileName] usingResourceFork:NO];
        return result == zkSucceeded;
    }
    @catch (NSException *exception)
    {
       return NO;
    }
    
    return NO;
}

the result is "cat 2.pdf" instead of "cat.pdf". NSFileManager correctly delete existing file, in fact only "cat 2.pdf" will exist.. but I need for the correct file name, any suggestion?

**Comment by kolpanic** [comment]
I have no idea what's going on here. Try stepping with the debugger.

However, if your zip archive contains a single reasonably-sized file, you may want to use ZKDataArchive instead, expanding to a NSData object then writing that to a file.

**Comment by H725-79** [comment]
Using ZKDataArchive solve the problem:

@try
    {
        NSMutableData *data = [NSMutableData dataWithContentsOfFile:source];
        ZKDataArchive *archive = [ZKDataArchive archiveWithArchiveData:data];
        result = [archive inflateInFolder:dir withFolderName:dir.lastPathComponent usingResourceFork:NO];
        return result == zkSucceeded;
    }

BTW what "withFolderName" parameter stand for? No really idea if I've done this correctly..

Thanks in advance
